import type { FixtureDef } from '../model/types';
import { createRegistry } from './registry';

/**
 * Strippable fixtures. Yields come from the design board; recharge times are doubled from it
 * (so a hot spot can't just be farmed) and work times are a little longer. Metals and the names
 * of the two unnamed "(name)" fixtures (Pneumatic Air Line, Radiator) are assumptions.
 *
 * `footprint` is each object's real size on the floor (its hitbox); the 3D models in
 * game/render/models/ are built to the same dimensions. `requires` gates the technical ones
 * behind gear tiers or worker level, so the bigger prizes open up as a career grows.
 */
export const FIXTURES = createRegistry<FixtureDef>('fixture', [
  {
    id: 'copper-pile',
    name: 'Abandoned Copper Pile',
    glyph: 'C',
    type: 'free',
    metal: 'copper',
    yield: { min: 1.5, max: 1.5 },
    recharge: { min: 120, max: 240 },
    workSeconds: 4,
    risk: 'very high',
    footprint: { w: 0.8, d: 0.8, anchor: 'center' },
    color: 0xd9822b,
  },
  {
    id: 'drinking-fountain',
    name: 'Drinking Fountain',
    glyph: 'F',
    type: 'plumbing',
    metal: 'brass',
    yield: { min: 1, max: 1 },
    recharge: { min: 90, max: 120 },
    workSeconds: 5,
    risk: 'high',
    footprint: { w: 0.55, d: 0.46, anchor: 'wall' },
    color: 0x90caf9,
  },
  {
    id: 'wall-heater',
    name: 'Wall Heater',
    glyph: 'H',
    type: 'hvac',
    metal: 'copper',
    yield: { min: 1, max: 1 },
    recharge: { min: 90, max: 120 },
    workSeconds: 5,
    risk: 'high',
    footprint: { w: 0.85, d: 0.31, anchor: 'wall' },
    color: 0xff7043,
  },
  {
    id: 'air-line',
    name: 'Pneumatic Air Line',
    glyph: 'A',
    type: 'hvac',
    metal: 'copper',
    yield: { min: 0.8, max: 1.2 },
    recharge: { min: 90, max: 120 },
    workSeconds: 5,
    risk: 'high',
    footprint: { w: 0.5, d: 0.23, anchor: 'wall' },
    color: 0x80cbc4,
  },
  {
    id: 'radiator',
    name: 'Radiator',
    glyph: 'R',
    type: 'hvac',
    metal: 'aluminum',
    yield: { min: 0.8, max: 1.2 },
    recharge: { min: 90, max: 120 },
    workSeconds: 5,
    risk: 'medium',
    footprint: { w: 0.9, d: 0.27, anchor: 'wall' },
    color: 0xbcaaa4,
  },
  {
    id: 'toilet',
    name: 'Toilet',
    glyph: 'T',
    type: 'plumbing',
    metal: 'brass',
    yield: { min: 0.25, max: 0.75 },
    recharge: { min: 60, max: 90 },
    workSeconds: 4,
    risk: 'medium',
    footprint: { w: 0.5, d: 0.68, anchor: 'wall' },
    color: 0xeceff1,
  },
  {
    id: 'mop-sink',
    name: 'Mop Sink',
    glyph: 'M',
    type: 'plumbing',
    metal: 'brass',
    yield: { min: 0.25, max: 0.75 },
    recharge: { min: 60, max: 90 },
    workSeconds: 4,
    risk: 'low',
    footprint: { w: 0.7, d: 0.65, anchor: 'wall' },
    color: 0x78909c,
  },
  {
    id: 'lamp',
    name: 'Desk Lamp',
    glyph: 'l',
    type: 'free',
    metal: 'copper',
    yield: { min: 0.2, max: 0.35 },
    recharge: { min: 60, max: 90 },
    workSeconds: 2.5,
    risk: 'low',
    footprint: { w: 0.6, d: 0.45, anchor: 'center' },
    color: 0xfff176,
  },
  {
    id: 'desk',
    name: 'Student Desk',
    glyph: 'k',
    type: 'free',
    metal: 'steel',
    yield: { min: 0.4, max: 0.6 },
    recharge: { min: 60, max: 90 },
    workSeconds: 3,
    risk: 'low',
    footprint: { w: 0.7, d: 0.8, anchor: 'center' },
    color: 0x8d6e63,
  },
  // --- Restrooms ---
  {
    id: 'urinal',
    name: 'Urinal',
    glyph: 'U',
    type: 'plumbing',
    metal: 'brass',
    yield: { min: 0.4, max: 0.7 },
    recharge: { min: 60, max: 90 },
    workSeconds: 4,
    risk: 'medium',
    footprint: { w: 0.45, d: 0.35, anchor: 'wall' },
    color: 0xf5f5f5,
  },
  {
    id: 'sink',
    name: 'Bathroom Sink',
    glyph: 'W',
    type: 'plumbing',
    metal: 'brass',
    yield: { min: 0.3, max: 0.6 },
    recharge: { min: 60, max: 90 },
    workSeconds: 3.5,
    risk: 'medium',
    footprint: { w: 0.6, d: 0.45, anchor: 'wall' },
    color: 0xeceff1,
  },
  {
    id: 'hand-dryer',
    name: 'Hand Dryer',
    glyph: 'Y',
    type: 'free',
    metal: 'copper',
    yield: { min: 0.3, max: 0.5 },
    recharge: { min: 90, max: 120 },
    workSeconds: 3.5,
    risk: 'medium',
    footprint: { w: 0.35, d: 0.22, anchor: 'wall' },
    color: 0xb0bec5,
    requires: { gear: { tools: 1 } },
  },
  // --- Science lab ---
  {
    id: 'lab-bench',
    name: 'Lab Gas Taps',
    glyph: 'g',
    type: 'plumbing',
    metal: 'brass',
    yield: { min: 0.4, max: 0.6 },
    recharge: { min: 60, max: 90 },
    workSeconds: 3.5,
    risk: 'medium',
    footprint: { w: 0.9, d: 0.6, anchor: 'center' },
    color: 0x37474f,
  },
  // --- Technical fixtures: need gear or experience ---
  {
    id: 'cooler-coils',
    name: 'Walk-in Cooler Coils',
    glyph: 'J',
    type: 'hvac',
    metal: 'copper',
    yield: { min: 1.2, max: 1.6 },
    recharge: { min: 150, max: 210 },
    workSeconds: 6,
    risk: 'high',
    footprint: { w: 0.9, d: 0.55, anchor: 'wall' },
    color: 0x90a4ae,
    requires: { gear: { tools: 1 } },
  },
  {
    id: 'electrical-panel',
    name: 'Electrical Panel',
    glyph: 'G',
    type: 'free',
    metal: 'copper',
    yield: { min: 1.5, max: 2 },
    recharge: { min: 150, max: 210 },
    workSeconds: 6,
    risk: 'high',
    footprint: { w: 0.7, d: 0.22, anchor: 'wall' },
    color: 0x9e9e9e,
    requires: { gear: { gloves: 1 } },
  },
  {
    id: 'trophy-case',
    name: 'Trophy Case',
    glyph: 'X',
    type: 'free',
    metal: 'brass',
    yield: { min: 1.5, max: 2.5 },
    recharge: { min: 180, max: 240 },
    workSeconds: 6,
    risk: 'very high',
    footprint: { w: 0.95, d: 0.45, anchor: 'wall' },
    color: 0xd4af37,
    requires: { gear: { tools: 2 } },
  },
  {
    id: 'server-rack',
    name: 'Server Rack',
    glyph: 'N',
    type: 'free',
    metal: 'copper',
    yield: { min: 1.2, max: 2 },
    recharge: { min: 150, max: 210 },
    workSeconds: 6.5,
    risk: 'high',
    footprint: { w: 0.6, d: 0.8, anchor: 'wall' },
    color: 0x263238,
    requires: { level: 4 },
  },
  {
    id: 'chiller',
    name: 'Chiller Compressor',
    glyph: 'I',
    type: 'hvac',
    metal: 'copper',
    yield: { min: 3, max: 4 },
    recharge: { min: 240, max: 300 },
    workSeconds: 9,
    risk: 'very high',
    footprint: { w: 0.95, d: 0.95, anchor: 'center' },
    color: 0x607d8b,
    requires: { level: 6, gear: { tools: 3 } },
  },
]);

export const fixtureByGlyph = (glyph: string) => FIXTURES.all.find((f) => f.glyph === glyph);
