import type { FixtureDef } from '../model/types';
import { createRegistry } from './registry';

/**
 * Strippable fixtures. Yields/recharge come from the design board; metals and the names of
 * the two unnamed "(name)" fixtures (Pneumatic Air Line, Radiator) are assumptions.
 */
export const FIXTURES = createRegistry<FixtureDef>('fixture', [
  {
    id: 'copper-pile',
    name: 'Abandoned Copper Pile',
    glyph: 'C',
    type: 'free',
    metal: 'copper',
    yield: { min: 1.5, max: 1.5 },
    recharge: { min: 60, max: 120 },
    workSeconds: 3,
    risk: 'very high',
    cover: 'low',
    color: 0xd9822b,
  },
  {
    id: 'drinking-fountain',
    name: 'Drinking Fountain',
    glyph: 'F',
    type: 'plumbing',
    metal: 'brass',
    yield: { min: 1, max: 1 },
    recharge: { min: 45, max: 60 },
    workSeconds: 4,
    risk: 'high',
    cover: 'low',
    color: 0x90caf9,
  },
  {
    id: 'wall-heater',
    name: 'Wall Heater',
    glyph: 'H',
    type: 'hvac',
    metal: 'copper',
    yield: { min: 1, max: 1 },
    recharge: { min: 45, max: 60 },
    workSeconds: 4,
    risk: 'high',
    cover: 'low',
    color: 0xff7043,
  },
  {
    id: 'air-line',
    name: 'Pneumatic Air Line',
    glyph: 'A',
    type: 'hvac',
    metal: 'copper',
    yield: { min: 0.8, max: 1.2 },
    recharge: { min: 45, max: 60 },
    workSeconds: 4,
    risk: 'high',
    cover: 'none',
    color: 0x80cbc4,
  },
  {
    id: 'radiator',
    name: 'Radiator',
    glyph: 'R',
    type: 'hvac',
    metal: 'aluminum',
    yield: { min: 0.8, max: 1.2 },
    recharge: { min: 45, max: 60 },
    workSeconds: 4,
    risk: 'medium',
    cover: 'low',
    color: 0xbcaaa4,
  },
  {
    id: 'toilet',
    name: 'Toilet',
    glyph: 'T',
    type: 'plumbing',
    metal: 'brass',
    yield: { min: 0.25, max: 0.75 },
    recharge: { min: 30, max: 45 },
    workSeconds: 3,
    risk: 'medium',
    cover: 'low',
    color: 0xeceff1,
  },
  {
    id: 'mop-sink',
    name: 'Mop Sink',
    glyph: 'M',
    type: 'plumbing',
    metal: 'brass',
    yield: { min: 0.25, max: 0.75 },
    recharge: { min: 30, max: 45 },
    workSeconds: 3,
    risk: 'low',
    cover: 'low',
    color: 0x78909c,
  },
  {
    id: 'lamp',
    name: 'Desk Lamp',
    glyph: 'l',
    type: 'free',
    metal: 'copper',
    yield: { min: 0.2, max: 0.35 },
    recharge: { min: 30, max: 45 },
    workSeconds: 2,
    risk: 'low',
    cover: 'none',
    color: 0xfff176,
  },
  {
    id: 'desk',
    name: 'Student Desk',
    glyph: 'k',
    type: 'free',
    metal: 'steel',
    yield: { min: 0.4, max: 0.6 },
    recharge: { min: 30, max: 45 },
    workSeconds: 2.5,
    risk: 'low',
    cover: 'low',
    color: 0x8d6e63,
  },
]);

export const fixtureByGlyph = (glyph: string) => FIXTURES.all.find((f) => f.glyph === glyph);
