import type { SkillDef, SkillTreeDef } from '../model/types';
import { createRegistry } from './registry';

/**
 * Four skill trees. Each opens with one root skill, forks into two choices, rejoins, and ends
 * in a 2-point capstone. A skill unlocks once ANY of its `requires` is owned.
 */
export const SKILL_TREES = createRegistry<SkillTreeDef>('skill tree', [
  {
    id: 'shadow',
    name: 'Shadow',
    blurb: 'Stay unseen',
    color: 0x9575cd,
  },
  {
    id: 'hustle',
    name: 'Hustle',
    blurb: 'Work faster, carry more',
    color: 0xf0a04b,
  },
  {
    id: 'dealer',
    name: 'Wheeler-Dealer',
    blurb: 'Money and favours',
    color: 0x66bb6a,
  },
  {
    id: 'craft',
    name: 'Craftsman',
    blurb: 'Cleaner pulls, bigger finds',
    color: 0x4fc3f7,
  },
]);

export const SKILLS = createRegistry<SkillDef>('skill', [
  // Shadow
  {
    id: 'soft-steps',
    tree: 'shadow',
    tier: 1,
    name: 'Soft Steps',
    description: 'Everyone notices you 10% slower.',
    cost: 1,
    requires: [],
    effect: { noticeMult: 0.9 },
  },
  {
    id: 'night-owl',
    tree: 'shadow',
    tier: 2,
    name: 'Night Owl',
    description: 'Dim and dark rooms hide you much better.',
    cost: 1,
    requires: ['soft-steps'],
    effect: { darkBonus: 0.45 },
  },
  {
    id: 'rubber-soles',
    tree: 'shadow',
    tier: 2,
    name: 'Rubber Soles',
    description: 'Sprinting and squeaky wet floors carry half as far.',
    cost: 1,
    requires: ['soft-steps'],
    effect: { noiseMult: 0.5 },
  },
  {
    id: 'smooth-hands',
    tree: 'shadow',
    tier: 3,
    name: 'Smooth Hands',
    description: 'Scrapping is 25% harder to notice.',
    cost: 1,
    requires: ['night-owl', 'rubber-soles'],
    effect: { scrapNoticeMult: 0.75 },
  },
  {
    id: 'ghost',
    tree: 'shadow',
    tier: 4,
    name: 'Ghost',
    description: 'Noticed 15% slower again, and suspicion fades twice as fast once you slip away.',
    cost: 2,
    requires: ['smooth-hands'],
    effect: { noticeMult: 0.85, decayMult: 2 },
  },
  // Hustle
  {
    id: 'quick-hands',
    tree: 'hustle',
    tier: 1,
    name: 'Quick Hands',
    description: 'Scrap 12% faster.',
    cost: 1,
    requires: [],
    effect: { scrapRateMult: 1.12 },
  },
  {
    id: 'second-wind',
    tree: 'hustle',
    tier: 2,
    name: 'Second Wind',
    description: '+1s of sprint, and stamina comes back 40% faster.',
    cost: 1,
    requires: ['quick-hands'],
    effect: { staminaBonus: 1, staminaRegenMult: 1.4 },
  },
  {
    id: 'deep-pockets',
    tree: 'hustle',
    tier: 2,
    name: 'Deep Pockets',
    description: '+0.5 bag capacity.',
    cost: 1,
    requires: ['quick-hands'],
    effect: { capacityBonus: 0.5 },
  },
  {
    id: 'lock-pro',
    tree: 'hustle',
    tier: 3,
    name: 'Lock Pro',
    description: 'Unlock doors 1s faster.',
    cost: 1,
    requires: ['second-wind', 'deep-pockets'],
    effect: { unlockReduction: 1 },
  },
  {
    id: 'overtime',
    tree: 'hustle',
    tier: 4,
    name: 'Overtime',
    description: 'Every shift lasts a minute longer.',
    cost: 2,
    requires: ['lock-pro'],
    effect: { shiftBonusSeconds: 60 },
  },
  // Wheeler-Dealer
  {
    id: 'haggler',
    tree: 'dealer',
    tier: 1,
    name: 'Haggler',
    description: 'Scrap sells for 10% more.',
    cost: 1,
    requires: [],
    effect: { saleMult: 1.1 },
  },
  {
    id: 'coupon-clipper',
    tree: 'dealer',
    tier: 2,
    name: 'Coupon Clipper',
    description: 'Everything at the hardware store is 15% cheaper.',
    cost: 1,
    requires: ['haggler'],
    effect: { shopDiscount: 0.15 },
  },
  {
    id: 'scrap-sense',
    tree: 'dealer',
    tier: 2,
    name: 'Scrap Sense',
    description: 'Stripped fixtures are ready again 25% sooner.',
    cost: 1,
    requires: ['haggler'],
    effect: { rechargeMult: 0.75 },
  },
  {
    id: 'union-rep',
    tree: 'dealer',
    tier: 3,
    name: 'Union Rep',
    description: '+1 heart: it takes one more warning to get fired.',
    cost: 1,
    requires: ['coupon-clipper', 'scrap-sense'],
    effect: { extraHearts: 1 },
  },
  {
    id: 'smooth-talker',
    tree: 'dealer',
    tier: 4,
    name: 'Smooth Talker',
    description: 'The first time you’re caught each shift, you talk your way out of the warning.',
    cost: 2,
    requires: ['union-rep'],
    effect: { catchForgiveness: 1 },
  },
  // Craftsman
  {
    id: 'steady-hands',
    tree: 'craft',
    tier: 1,
    name: 'Steady Hands',
    description: 'Fewer botched and rough jobs.',
    cost: 1,
    requires: [],
    effect: { efficiency: 0.06 },
  },
  {
    id: 'salvager',
    tree: 'craft',
    tier: 2,
    name: 'Salvager',
    description: 'Rough jobs and bonus finds both yield more.',
    cost: 1,
    requires: ['steady-hands'],
    effect: { salvage: 0.2 },
  },
  {
    id: 'feel-for-it',
    tree: 'craft',
    tier: 2,
    name: 'Feel for It',
    description: 'Cleaner pulls again, and a little faster.',
    cost: 1,
    requires: ['steady-hands'],
    effect: { efficiency: 0.06, scrapRateMult: 1.05 },
  },
  {
    id: 'old-pro',
    tree: 'craft',
    tier: 3,
    name: 'Old Pro',
    description: 'Bonus finds come up far more often.',
    cost: 1,
    requires: ['salvager', 'feel-for-it'],
    effect: { efficiency: 0.08 },
  },
  {
    id: 'master-scrapper',
    tree: 'craft',
    tier: 4,
    name: 'Master Scrapper',
    description: 'Never come away empty-handed again, and every pull yields a bit more.',
    cost: 2,
    requires: ['old-pro'],
    effect: { noBotch: 1, salvage: 0.15 },
  },
]);

export const skillsInTree = (tree: string) => SKILLS.all.filter((s) => s.tree === tree);
