import { parseAsciiLevel } from '../asciiLevel';
import type { RoomDef } from '../types';

/**
 * Lincoln Elementary, expanded. The van waits in the parking lot on the west side; the
 * further east you go, the richer and harder the scrap:
 * - West: classrooms, the main office (Mr. Gravy's turf, with a trophy case) and the library.
 * - Centre: restrooms, the science lab, the cafeteria, kitchen and teachers' lounge.
 * - East: the gym and locker room, the music room, and the technical rooms: electrical
 *   (gloves), server (experience), mechanical and boiler (security doors).
 * Lockers, shelves, bookshelves, stalls and boilers block sight; desks, tables, benches,
 * counters, bins and planters are cover. Generated by scripts/gen-school-map.py; edit that.
 * See asciiLevel.ts for the legend.
 */
const rooms: RoomDef[] = [
  { id: 'parking', name: 'Parking Lot', kind: 'exterior', rect: { col: 0, row: 0, w: 8, h: 44 } },
  {
    id: 'main-hall',
    name: 'Main Hallway',
    kind: 'hallway',
    rect: { col: 9, row: 19, w: 82, h: 4 },
  },
  {
    id: 'west-hall-n',
    name: 'West Hallway',
    kind: 'hallway',
    rect: { col: 30, row: 1, w: 3, h: 18 },
  },
  {
    id: 'west-hall-s',
    name: 'West Hallway',
    kind: 'hallway',
    rect: { col: 30, row: 23, w: 3, h: 20 },
  },
  {
    id: 'east-hall-n',
    name: 'East Hallway',
    kind: 'hallway',
    rect: { col: 60, row: 1, w: 3, h: 18 },
  },
  {
    id: 'east-hall-s',
    name: 'East Hallway',
    kind: 'hallway',
    rect: { col: 60, row: 23, w: 3, h: 20 },
  },
  {
    id: 'north-hall-w',
    name: 'North Hallway',
    kind: 'hallway',
    rect: { col: 9, row: 9, w: 21, h: 2 },
  },
  {
    id: 'north-hall-c',
    name: 'North Hallway',
    kind: 'hallway',
    rect: { col: 33, row: 9, w: 27, h: 2 },
  },
  {
    id: 'south-hall-w',
    name: 'South Hallway',
    kind: 'hallway',
    rect: { col: 9, row: 32, w: 21, h: 2 },
  },
  {
    id: 'south-hall-e',
    name: 'South Hallway',
    kind: 'hallway',
    rect: { col: 63, row: 32, w: 28, h: 2 },
  },
  {
    id: 'class-101',
    name: 'Classroom 101',
    kind: 'classroom',
    rect: { col: 9, row: 1, w: 10, h: 7 },
  },
  {
    id: 'class-102',
    name: 'Classroom 102',
    kind: 'classroom',
    rect: { col: 20, row: 1, w: 9, h: 7 },
  },
  { id: 'office', name: 'Main Office', kind: 'office', rect: { col: 9, row: 12, w: 10, h: 6 } },
  { id: 'library', name: 'Library', kind: 'library', rect: { col: 20, row: 12, w: 9, h: 6 } },
  {
    id: 'boys-room',
    name: "Boys' Restroom",
    kind: 'restroom',
    rect: { col: 34, row: 1, w: 7, h: 7 },
  },
  {
    id: 'girls-room',
    name: "Girls' Restroom",
    kind: 'restroom',
    rect: { col: 42, row: 1, w: 8, h: 7 },
  },
  { id: 'janitor', name: 'Janitor Closet', kind: 'closet', rect: { col: 51, row: 1, w: 8, h: 7 } },
  { id: 'science-lab', name: 'Science Lab', kind: 'lab', rect: { col: 34, row: 12, w: 15, h: 6 } },
  {
    id: 'class-103',
    name: 'Classroom 103',
    kind: 'classroom',
    rect: { col: 50, row: 12, w: 9, h: 6 },
  },
  { id: 'gym', name: 'Gymnasium', kind: 'gym', rect: { col: 64, row: 1, w: 19, h: 17 } },
  {
    id: 'locker-room',
    name: 'Locker Room',
    kind: 'restroom',
    rect: { col: 84, row: 1, w: 7, h: 17 },
  },
  {
    id: 'class-104',
    name: 'Classroom 104',
    kind: 'classroom',
    rect: { col: 9, row: 24, w: 10, h: 7 },
  },
  {
    id: 'class-105',
    name: 'Classroom 105',
    kind: 'classroom',
    rect: { col: 20, row: 24, w: 9, h: 7 },
  },
  {
    id: 'class-106',
    name: 'Classroom 106',
    kind: 'classroom',
    rect: { col: 9, row: 35, w: 10, h: 8 },
  },
  { id: 'supply', name: 'Supply Closet', kind: 'closet', rect: { col: 20, row: 35, w: 5, h: 8 } },
  {
    id: 'staff-room',
    name: 'Staff Restroom',
    kind: 'restroom',
    rect: { col: 26, row: 35, w: 3, h: 8 },
  },
  {
    id: 'cafeteria',
    name: 'Cafeteria',
    kind: 'cafeteria',
    rect: { col: 34, row: 24, w: 17, h: 19 },
  },
  { id: 'kitchen', name: 'Kitchen', kind: 'kitchen', rect: { col: 52, row: 24, w: 7, h: 10 } },
  {
    id: 'lounge',
    name: "Teachers' Lounge",
    kind: 'lounge',
    rect: { col: 52, row: 35, w: 7, h: 8 },
  },
  { id: 'music', name: 'Music Room', kind: 'classroom', rect: { col: 64, row: 24, w: 9, h: 7 } },
  {
    id: 'electrical',
    name: 'Electrical Room',
    kind: 'mechanical',
    rect: { col: 74, row: 24, w: 5, h: 7 },
  },
  {
    id: 'mechanical',
    name: 'Mechanical Room',
    kind: 'mechanical',
    rect: { col: 80, row: 24, w: 11, h: 7 },
  },
  { id: 'server', name: 'Server Room', kind: 'mechanical', rect: { col: 64, row: 35, w: 7, h: 8 } },
  { id: 'boiler', name: 'Boiler Room', kind: 'boiler', rect: { col: 72, row: 35, w: 19, h: 8 } },
];

// prettier-ignore
const map = [
  '========####################################################################################',
  '========#..R....R..#..R...R..#...#UUU.TqT#.TqTqTq.#M.M..A..#...#..b.b.b.b.b.b.b.b..#.UU.TqT#',
  '========#..........#.........#O..#.......#........#.......h#...#...................#.......#',
  '=======p#..k..k..k.#.k..k..k.#O..#......W#.......W#.......h#..O#...................#......O#',
  '========#....S.....#...S.....#...#......W#.......W#..Q.....#..O#H.................H#......O#',
  '========#..k..k..k.#.k..k..k.#.3.#......Y#.......Y#........#..O#...................#......O#',
  '========#H......S..#......S..#...#.n.....#.n......#....Z...#...D......S............#......O#',
  '========#.l..E.....#..E...l..#...#.......#........#n.......#...#...................#.......#',
  '========######D#########D#####...####D#######D########L#####...#..................A#......W#',
  '=======p#........OOOO.....F.........................H..........#.........E.........D......W#',
  '========#.............................OO.......OOO.............#...................#.......#',
  '========######D#########D#####...#######D#############D#####...#...................#......Y#',
  '========#..X.X..F.h#rrr...rrr#..F#............R..#..R...R..#H..#..................H#b......#',
  '========#..........#.........#O..#F.............h#.........#...D.............S.....#b......#',
  '========#..........#r..t.t...#O..#..g..g..g.....h#.k..k..k.#..O#...................#......O#',
  '=======p#.k....1...#r...S....#O..#....S......E...#...S.....#..O#...................#......O#',
  '========#........l.#r..t..l..#...#..g..g..g......#.k..k....#...#F................Z.#..n....#',
  '========#p........Z#.........#...#.........S.....#.......l.#...#...................#.......#',
  '========####D#############D###...###########D#########D#####...#########D##############D####',
  '========#.OO.O......F..H...........OOO..n....H..OOO.Fb...........OOO.H.....F..OOO.......H..#',
  '==VVV===D.............................................................................5....#',
  '==VVV=P=D.....................................2............................................#',
  '========#.......OOO..H....b.F.....p......OOO...H.......OOO......p.....OOO.n........HF......#',
  '========######D#########D#####...#####DD######D#############...#####D#######################',
  '========#.l........#.........#...#..........n......#.cccc..#...#.........#G.G.G#A....G.....#',
  '========#..k..k..k.#.k..k..k.#...#F................#......J#O..#..k..k.l.#.....#...........#',
  '========#....S.....#...S.....#..O#..tt...tt...tt...#c.....J#O..#....S....#.....#...I...I...#',
  '=======p#..k..k..k.#.k..k....#..O#..tt...tt...tt...#c......#...#..k..k...#.....#...........#',
  '========#.......S.H#.......l.#..O#.................D.......D...#.......S.#.....#..........A#',
  '========#....E.....#.........#...#.....S....E......#.......#..F#.........#....h#...........#',
  '========#..R....R..#..R...R..#...#................H#W......#...#..R...R..#.....#...........#',
  '========######################...#..tt...tt...tt...#.......#...#############L########K######',
  '========D.........F..............#..tt...tt...tt...#......h#......OOO..OO...............H..#',
  '========#..OOO...........H.......D.................#M......#..................F............#',
  '========######D#######L####D##...#..........S......#########...####L############K###########',
  '========#..........#.....#...#...#H..............n.#F......#...#N.N.N..#.A.................#',
  '=======p#..k..k..k.#h....#..W#...#.................#......b#O..#......N#................C..#',
  '========#H...S.....#h....#...#..O#..tt...tt...tt...#..tt..b#O..#.......#...BB.......BB.....#',
  '========#..k..k..k.#....h#..Y#..O#..tt...tt...tt...#.......D...#.......#...BB.......BB.....#',
  '========#..........#....h#...#...#..............S..#W......#...#.......#.................Z.#',
  '========#.l....S...#.....#...#F..#..S..............#....k..#.4.#..k....#.......C...........#',
  '=======p#..........#..C..#...#...#.....n..........F#.l.....#...#....l..#..................A#',
  '========#..R....R..#.Z...#.T.#...#.................#.....Z.#...#.......#.........C.........#',
  '========####################################################################################',
];

export const SCHOOL_LEVEL = parseAsciiLevel({
  id: 'school',
  name: 'Lincoln Elementary',
  map,
  rooms,
  bossRoute: '12345',
});
